spring.application.name=Final

spring.datasource.url=jdbc:mysql://localhost:3306/student_mgmt_v5
spring.datasource.username=root
# password may depend on your localhost password 
# in my case my password is admin -wytm

#spring.datasource.password=root
spring.datasource.password=${DB_PASSWORD:admin}
